# NUMPY

- Introduction
- Installing NumPy
- Data types in NumPy
- Numpy arrays
- Attributes of NumPy
  - ndim
  - Shape
  - size
  - Datatype
  - Size
- Creating a numpy array
  - 2 ways.
- Arrays with specific values
- Arrays with random values
- Arrays within a range
- Load text file using loadtxt() and gentxt()
- Resize an array
- Reshape complex array
- Reshape an array
- Numpy Operations
  -  indexing and array slicing
  -  extract portion of the array
- Multidimensional array
- Flattening an array
- Linear algebra on n-dimensional arrays
- Mathematical operations 
  - Addition
  - Subtraction
  - Multiplication
  - Dot product
  - Division
  - Modulus
  - Exponents
- Conditional operators
- Mathematical and statistical functions:
- Sum
- Transpose
- Broadcasting in NumPy

### Introduction

What is NumPy?

- NumPy is the fundamental package for scientific computing in Python.
- Numpy arrays are faster than pythan lists as they consume less memoery and are easier to use.
- It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices)
- Used to perform fast operations on arrays.
- Supports the below opearations.
  - Mathematical
  - Logical 
  - Shape manipulation
  - Sorting
  - Selecting
  - I/O
  - Discrete Fourier transforms
  - Basic linear algebra
  - Basic statistical operations
  - Random simulation and much more.

Basics

- NumPy’s main object is the homogeneous multidimensional array. 
- It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. 
- In NumPy dimensions are called axes.

## Attributes of a numpy array:

- Rank(ndarray.ndim): the number of axes (dimensions) of the array.

- Shape(ndarray.shape): the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. 

- Size(ndarray.size): the total number of elements of the array. This is equal to the product of the elements of shape.

- Data Type(ndarray.dtype) :an object describing the type of the elements in the array.

- Item size(ndarray.itemsize) : the size in bytes of each element of the array.

- ndarray.data : the buffer containing the actual elements of the array. 

### Data types in Numpy:

https://numpy.org/doc/stable/user/basics.types.html

Numpy needs python preinstalled.

Numpy can be installed with conda or pip.

conda:
    # Best practice, use an environment rather than install in the base env
    conda create -n my-env
    conda activate my-env
    # If you want to install from conda-forge
    conda config --env --add channels conda-forge
    # The actual install command
    conda install numpy
pip:
    pip install numpy

Import numpy

In [1]:
import numpy as np

In [ ]:
Quick example

In [2]:
a = np.arange(6)

In [4]:
print(a)

[0 1 2 3 4 5]


- Creating a numpy array:
    - Creating a NumPy array by passing a Python list
    - Creating NumPy array by passing a Python tuple
    

### Creating a NumPy array by passing a Python list

In [6]:
# Creating a NumPy array by passing a Python list
import numpy as np
test_list= [50, 12, 67, 23]
my_np_arr=  np.array(test_list)

In [7]:
print(my_np_arr)

[50 12 67 23]


### Creating NumPy array by passing a Python tuple

In [8]:
import numpy as np
my_tuple = (88, 17, 45, 76)
my_tuple_arr = np.array(my_tuple)

In [9]:
print(my_tuple_arr)

[88 17 45 76]


### Special cases

In [10]:
# create array of zeros
import numpy as np
tupple = (3,4)
my_zero_array = np.zeros(tupple, dtype=np.int16)
print(my_zero_array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [11]:
# create array of ones
import numpy as np
tupple = (3,4)
my_ones_array = np.ones(tupple, dtype=np.int16)
print(my_ones_array)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [13]:
# create array with specific values
import numpy as np
tupple = (3,4)
my_six_array = np.full(tupple,6, dtype=np.int16)
print(my_six_array)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [15]:
#create identify matrix or array, below creates an identify matrix or 4*4
import numpy as np
my_identity_array = np.identity(4, dtype=np.int16)
print(my_identity_array)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [18]:
# create array with random values. The below NumPy array will have random float values between 0.0 and 1.0
import numpy as np
my_random_arr = np.random.random((3, 4))
print(my_random_arr)

[[0.25242074 0.71611876 0.05881364 0.50431457]
 [0.74171015 0.38333655 0.14169848 0.12490287]
 [0.57940354 0.42254173 0.23911349 0.66260453]]


In [19]:
# create empty with random values
tup = (3, 4)
my_uninitialized_array = np.empty(tup)

In [20]:
my_uninitialized_array

array([[0.25242074, 0.71611876, 0.05881364, 0.50431457],
       [0.74171015, 0.38333655, 0.14169848, 0.12490287],
       [0.57940354, 0.42254173, 0.23911349, 0.66260453]])

In [ ]:
#check empty vs random

### arrays within specific range

- By passing a range of values (using arange() function of NumPy)
    np.arange(start val,end val,gap between each value)
- By passing an equally spaced range of values (using linspace() function of NumPy)
    np.linspace(start val, end val, nf of values needed)

In [21]:
# By passing a range of values (using arange() function of NumPy)
range_array = np.arange(10,50,5)
print(range_array)

[10 15 20 25 30 35 40 45]


In [22]:
# By passing an equally spaced range of values (using linspace() function of NumPy)
spaced_array = np.linspace(10,50,5)
print(spaced_array)

[10. 20. 30. 40. 50.]


## Load text file using loadtxt() and gentxt()

There are two ways to load text from a file in NUMPY:
    
- using loadtxt() - does not handle missing values
- using gentxt() - handles missing value kind of scenarios

## Resize an array

- resize() function used. 
- Can be used to crate a new array of different size and dimensions
- Can be used to create a larger array of different size.

Syntax:

ndarray.resize(new_shape, refcheck=True)

In [ ]:
#Example

import numpy as np

my_arr = np.array([ [0,1], [2,3] ])

my_arr.resize( (2, 3) )

- Reshape an array

- reshape() function used.
- creates a new array of same size but odf diffent dimensions
- cannot be used to convert original array to bigger array.

Syntax:

ndarray.reshape(new_shape)

In [ ]:
## We know desired number of dimensions

my_arr = np.arange(6)
# we want to reshape this to 2*3 array
my_new_arr = my_arr.reshape(2,3)

In [ ]:
## We know number of columns but not number of rows

my_arr = np.arange(9)
# we know our array will have 3 columns but not sure of the number of rows
my_new_arr = my_arr.reshape(-1,3)

Reshape vs Resize

reshape used when we want to change dimensions of an array ubut with same number of elements
resize used when we need a larger array than orignal array

- Numpy Operations
 


 -  indexing and array slicing
# Index of a numpy array starts with 0 similar to python


In [ ]:
import numpy as np
arr = np.array([1, 10, 31, 2, 18, 9, 22])
#print 2nd element
print(arr[1])

#print element 1 to 5

print(arr[1:6])

#exract element with a gap of 2

print(arr[1: :2])

#reverse an array

print(arr[: : -1])

  -  extract portion of the array

In [ ]:
#creating a slice
new_slice = arr[1:4]
new_slice[1]= 4

#the above also affects the original array value arr.

#To avoid this, to create a slice, copy an array using copy()

latest_slice = arr[1:4].copy()

- Multidimensional array

Syntax: array[ row_start_index : row_end_index, column_start_index : column_end_index]

- multi_arr[1, 2]      -  to access value at row 1 and column 2
- multi_arr[1, :]      -  to access value at row 1 and all columns
- multi_arr[:, 1]      -  to access value at all rows and column 1

- Flattening an array

Flattening an array is the process of converting an n-d array to a 1-d array.

Done as some python libraries require 1 d array as input.

function  ravel() used

In [ ]:
#create an array of dimension 4*%
my_2d_arr = np.arange(20).reshape((4,5))

#flatten array to 1D array
myarr = my_2d_arr.ravel()

- Mathematical operations 
  - Addition : addition is element wise
  - Subtraction : subtraction is element wise
  - Multiplication : multiplicaiton is element wise and rpresented by *
  - Dot product : represnted by . Not element wise
  - Division : element wise and represented by /
  - Modulus : elementwise and rpresented by %
  - Exponents : elementwise. Represnted by **

In [ ]:
#Additon and subtraction
import numpy as np
a = np.array([ 20, 30, 40, 50])
b = np.arange(4)
sum_arr = a+b
diff_arr= a-b

In [ ]:
#Multiplication and Dot product

import numpy as np
A = np.array( [ [ 1,1], [0, 1] ] )
B = np.array( [ [2, 0], [3, 4] ] )
M = A*B
D= A.B

In [ ]:
#Division, modulus and exponent

import numpy as np
R = np.array( [ 20, 30, 40, 50] )
S = np.arange( 1, 5 )

D = R/S
M = R%S
Exp = R ** S

In [ ]:
import numpy as np
m = np.array( [ 20, -5, 30, 40] )

m < [15, 16, 35, 36]

- Conditional operators

Operators like >, <,>=,<= can be used

- Mathematical and statistical functions:
    
Below functions are available:
    
mean()  - used to find mean of an array
var() - used to find varience of an array
std() -  used to find standard deviation of an array
min() - used to find minimum element of an array
max() - used to find maximum element of an array
sum() - used to find sum of elements of an array. Can also be done across each axis or total array
prod() - used to find product of elements of an array

In [ ]:
X = np.array( [ [-2.5, 3.1, 7],
                [10, 11, 12] ] )
mean = X.mean()
varience = X.var(r)
std_dev = X.std()
min_ele = X.min()
max_ele = X.max()
product = X.prod()


In [ ]:
big_arr = array( [ [ [ 0, 1, 2, 3],
           [ 4, 5, 6, 7],
           [ 8, 9, 10, 11] ],

         [ [ 12, 13, 14 15],
           [ 16, 17, 18, 19],
           [ 20, 21, 22, 23] ] ] )

#total sum
sum_val = big_arr.sum()

#sum across axis 0 
zero_axis_sum = big_arr.sum(axis=0)

#sum across axis 1 
first_axis_sum = big_arr.sum(axis=0)

- Transpose

Interchange the rows and columns of a matrix

In [ ]:
M = np.arange(6).reshape(2, 3)
print("array is " M)
print("Transpose = ", M.T)

- Broadcasting in NumPy

Broadcasting is a conecept used in mathematical operations of numpy arrays.

Broadcasting, generally, tries to adjust the shape of one or both of the arrays to bring them to required matching shape, by copying the existing elements required number of times, so that the mathematical operation could be performed between the two NumPy arrays.

## Rules

- If the arrays don’t have the same rank then prepend the shape of the lower rank array with 1s until both shapes have the same length.
- The two arrays are compatible in a dimension if they have the same size in the dimension or if one of the arrays has size 1 in that dimension.
- The arrays can be broadcast together if they are compatible with all dimensions.
- After broadcasting, each array behaves as if it had shape equal to the element-wise maximum of shapes of the two input arrays.
- In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension.